sudo: required
language: c
dist : trusty
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
env:
    global:
        - LIBSODIUM_VER=1.0.12
        - MBEDTLS_VER=2.4.0
        - INSTALL_DIR=$HOME/build/release
        - DEPLOY_ARTIFACT=$HOME/build/ss-libev-${TRAVIS_OS_NAME}-${TRAVIS_COMPILER}.tar.gz
before_install:
    - git clone --recurse-submodules https://github.com/shadowsocks/shadowsocks-libev.git
    - mv shadowsocks-libev/* .
    - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          # All dependencies for macOS build. Some packages has been installed by travis so use reinstall.
          brew reinstall autoconf automake xmlto c-ares libev mbedtls libsodium asciidoc >> /dev/null 2>&1;
      else
          wget  https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VER/libsodium-$LIBSODIUM_VER.tar.gz;
          tar xvf libsodium-$LIBSODIUM_VER.tar.gz;
          pushd libsodium-$LIBSODIUM_VER;
          ./configure --prefix=/usr && make;
          sudo make install;
          popd;
          wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz;
          tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz;
          pushd mbedtls-$MBEDTLS_VER;
          make SHARED=1;
          sudo make install;
          popd;
          # Load cached docker images
          if [[ -d $HOME/docker ]]; then
              ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load";
          fi
      fi
addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - libc-ares-dev
            - libev-dev
            - asciidoc
            - xmlto
script:
    - ./autogen.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          ./configure --disable-documentation --with-mbedtls=/usr/local/opt/mbedtls --with-sodium=/usr/local/opt/libsodium --prefix=$INSTALL_DIR;
      else
          ./configure;
      fi
    - make
    - cd build && cmake ../ && make
    - make clean 
    - mkdir -p $INSTALL_DIR && make install
    - ls -al $INSTALL_DIR
    - tar -cvzf $DEPLOY_ARTIFACT $INSTALL_DIR
    
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
  - "$DEPLOY_ARTIFACT"
  
branches:
    only:
        - master
